Let'sUpgrade Data Science Essential Assignment 1(20-3-21)


Done By Sai Nandini Batta

In [118]:
import numpy as np #importin numpy 
import pandas as pd # importing pandas


In [119]:
array = np.arange(1,61) # creating numpy array(1-60)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [120]:
array.shape

(60,)

In [121]:
array[3]

4

In [122]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60])

In [123]:
array = np.arange(1,61).reshape(5,3,4)  #shaped the arry into 3d array
array   #Calling the array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]],

       [[37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]],

       [[49, 50, 51, 52],
        [53, 54, 55, 56],
        [57, 58, 59, 60]]])

# End of the Task1

# Q-2-Reshape above NumPy 3d array to 20*3

In [124]:
array = np.arange(1,61).reshape(20,3) #1 is start and 61 is stop number by default the array takes 1 to 60 numbers and displyas it

In [125]:
array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33],
       [34, 35, 36],
       [37, 38, 39],
       [40, 41, 42],
       [43, 44, 45],
       [46, 47, 48],
       [49, 50, 51],
       [52, 53, 54],
       [55, 56, 57],
       [58, 59, 60]])

# End of the Task 2

# Create a Numpy array of the student mark  and fin min,avg  of each student and min,avg of each subject

In [126]:
df = pd.DataFrame(data={'Maths': [58,62,85], 'Physics': [45,76,92], 'Chemisrty': [72,85,91],'English':[32,51,81]}, 
                  index=['a', 'b', 'c'])

# Convert the entire DataFrame
df.to_numpy()
# array([[1, 4, 7],
#        [2, 5, 8],
#        [3, 6, 9]])

# Convert specific columns
df[['Maths', 'Physics','Chemisrty','English']].to_numpy()
# array([[1, 7],
#        [2, 8],
#        [3, 9]])

array([[58, 45, 72, 32],
       [62, 76, 85, 51],
       [85, 92, 91, 81]], dtype=int64)

In [127]:
dfObj

Names  Ravi  Sunil  Sekhar  \
Subject                             Math    58     62      85   
Subject                          Physics    45     76      92   
Subject                        Chemisrty    72     85      91   
Subject                          English    32     51      81   
Min of each student  Min of each student     0      0       0   
Avg of each student  Avg of each student     0      0       0   

                    Min of each subject Average of each subject  
Subject                             nun                     nun  
Subject                             nun                     nun  
Subject                             nun                     nun  
Subject                             nun                     nun  
Min of each student                 nun                     nun  
Avg of each student                 nun                     nun

In [128]:
# List of tuples
students = [ ('Math', 58, 62 ,85,'nun','nun') ,
             ('Physics', 45, 76 ,92,'nun','nun' ) ,
             ('Chemisrty', 72, 85 ,91,'nun','nun' ) ,
             ('English', 32, 51 , 81,'nun','nun' ) ,
             ('Min of each student', 0, 0 , 0,'nun','nun') ,
             ('Avg of each student', 0, 0 , 0,'nun','nun')  ]
# Create DataFrame object from a list of tuples
dfObj = pd.DataFrame(students, columns = ['Names','Ravi' , 'Sunil', 'Sekhar','Min of each subject','Average of each subject'], index=['Subject', 'Subject', 'Subject' , 'Subject' , 'Min of each student' , 'Avg of each student'])

In [129]:
dfObj

Names  Ravi  Sunil  Sekhar  \
Subject                             Math    58     62      85   
Subject                          Physics    45     76      92   
Subject                        Chemisrty    72     85      91   
Subject                          English    32     51      81   
Min of each student  Min of each student     0      0       0   
Avg of each student  Avg of each student     0      0       0   

                    Min of each subject Average of each subject  
Subject                             nun                     nun  
Subject                             nun                     nun  
Subject                             nun                     nun  
Subject                             nun                     nun  
Min of each student                 nun                     nun  
Avg of each student                 nun                     nun

In [130]:
min_of_each_student_Ravi=min(58,45,72,32)
min_of_each_student_Ravi

32

In [131]:
min_of_each_student_Sunil=min(62,76,85,51)
min_of_each_student_Sunil



51

In [132]:
min_of_each_student_Sekhar=min(85,92,91,81)
min_of_each_student_Sekhar

81

In [133]:
Min_of_each_subject_Maths=min(58,62,85)
Min_of_each_subject_Maths

58

LetsUpgrade Data science Assignmint(20-3-2021)

Done By Sai Nandini Batta

In [134]:
Min_of_each_subject_Physics=min(45,76,92)
Min_of_each_subject_Physics

45

In [135]:
Min_of_each_subject_Chemisrty=min(72,85,91)
Min_of_each_subject_Chemisrty


72

In [136]:
Min_of_each_subject_English=min(32,51,81)
Min_of_each_subject_English

32

In [137]:
# to find avg of each subject and student

In [138]:
dfObj

Names  Ravi  Sunil  Sekhar  \
Subject                             Math    58     62      85   
Subject                          Physics    45     76      92   
Subject                        Chemisrty    72     85      91   
Subject                          English    32     51      81   
Min of each student  Min of each student     0      0       0   
Avg of each student  Avg of each student     0      0       0   

                    Min of each subject Average of each subject  
Subject                             nun                     nun  
Subject                             nun                     nun  
Subject                             nun                     nun  
Subject                             nun                     nun  
Min of each student                 nun                     nun  
Avg of each student                 nun                     nun

In [139]:
def Avg_of_each_student_Ravi(num):
    sum_num = 0
    for t in num:
        sum_num = sum_num + t           

    avg = sum_num / len(num)
    return avg

print("The average is", Avg_of_each_student_Ravi([58,45,72,32]))

The average is 51.75


In [140]:
def Avg_of_each_student_Sunil(num):
    sum_num = 0
    for t in num:
        sum_num = sum_num + t           

    avg = sum_num / len(num)
    return avg

print("The average is", Avg_of_each_student_Sunil([62,76,85,51]))

The average is 68.5


In [141]:
def Avg_of_each_student_Sekhar(num):
    sum_num = 0
    for t in num:
        sum_num = sum_num + t           

    avg = sum_num / len(num)
    return avg

print("The average is", Avg_of_each_student_Sekhar([85,92,91,81]))

The average is 87.25


In [142]:
def Average_of_each_subject_math(num):
    sum_num = 0
    for t in num:
        sum_num = sum_num + t           

    avg = sum_num / len(num)
    return avg

print("The average is", Average_of_each_subject_math([58,62,85]))

The average is 68.33333333333333


In [143]:
dfObj


Names  Ravi  Sunil  Sekhar  \
Subject                             Math    58     62      85   
Subject                          Physics    45     76      92   
Subject                        Chemisrty    72     85      91   
Subject                          English    32     51      81   
Min of each student  Min of each student     0      0       0   
Avg of each student  Avg of each student     0      0       0   

                    Min of each subject Average of each subject  
Subject                             nun                     nun  
Subject                             nun                     nun  
Subject                             nun                     nun  
Subject                             nun                     nun  
Min of each student                 nun                     nun  
Avg of each student                 nun                     nun

In [144]:
def Average_of_each_subject_Physics(num):
    sum_num = 0
    for t in num:
        sum_num = sum_num + t           

    avg = sum_num / len(num)
    return avg

print("The average is", Average_of_each_subject_math([45,76,92]))

The average is 71.0


In [145]:
def Average_of_each_subject_Chemistry(num):
    sum_num = 0
    for t in num:
        sum_num = sum_num + t           

    avg = sum_num / len(num)
    return avg

print("The average is", Average_of_each_subject_math([72,85,91]))

The average is 82.66666666666667


In [146]:
def Average_of_each_subject_English(num):
    sum_num = 0
    for t in num:
        sum_num = sum_num + t           

    avg = sum_num / len(num)
    return avg

print("The average is", Average_of_each_subject_math([32,51,81]))

The average is 54.666666666666664


# Calulated in Excel sheet And single solution

In [147]:
Studentdata=pd.read_excel("Letsupgrade Excel sheet.xlsx")

In [148]:
Studentdata  #All the asked task done in excel.

Unnamed: 0  Ravi  Sunil  Sekhar  Min(each subject)  \
0             Maths   58.0     62      85               58.0   
1            Pysichs  45.0     76      92               45.0   
2          Chemistry  72.0     85      91               72.0   
3            English  32.0     51      81               32.0   
4  Min(each student)  32.0     51      81                NaN   
5  Avg(Each Student)  47.8     65      86                NaN   

   Avg(Each subject)  
0              65.75  
1              64.50  
2              80.00  
3              49.00  
4                NaN  
5                NaN

End of the task 3

# Difference between Python list and array

"""What Is a List in Python?


A list is a data structure that's built into Python and holds a collection of items. 
Lists have a number of important characteristics:

List items are enclosed in square brackets, like this [item1, item2, item3].
Lists are ordered – i.e. the items in the list appear in a specific order. This enables us to use an index to access to any item.
Lists are mutable, which means you can add or remove items after a list's creation.
List elements do not need to be unique. Item duplication is possible, as each element has its own distinct place and can be accessed separately through the index.
Elements can be of different data types: you can combine strings, integers, and objects in the same list.

It can be writen as Lists are very easily created in Python:

list = [3, 6, 9, 12]
print(list)
print(type(list))"""

What Is an Array in Python?


"""An array is also a data structure that stores a collection of items. Like lists, arrays are ordered, mutable, enclosed in square brackets, and able to store non-unique items.

But when it comes to the array's ability to store different data types, the answer is not as straightforward. It depends on the kind of array used.

To use arrays in Python, you need to import either an array module or a NumPy package.
To use arrays in Python, you need to import either an array module or a NumPy package.

import array as arr
"""

Arrays need to be declared. Lists don't, 
Arrays can store data very compactly,
Arrays are great for numerical operations

List Can consist of elements belonging to different data types
But array Only consists of elements belonging to the same data type

End of the task4

Assignment complited